name: Build and Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    needs: build
    name: Check
    uses: Logius-standaarden/Automatisering/.github/workflows/check.yml@main    
  publish:
    needs: build
    name: Publish (Logius)
    uses: Logius-standaarden/Automatisering/.github/workflows/publish.yml@main
    secrets: inherit
